### ISSUE TITLE
Kelowna—Lake Country .. Liberal?

### ISSUE THREAD

**Issue by KelseyDH** [j3camero/canada-election-forecast#16]
2011 election results in Kelown-Lake Country:

```
2011 federal election redistributed results
Party   Vote     %
 Conservative   28,220  58.38
 New Democratic 10,329  21.37
 Liberal    5,546   11.47
 Green  4,244   8.78
```

Yet http://anyonebutharper.net/riding.php?riding_number=59014 gives a slight advantage to the Liberals in this seat.  I'm wondering what polling data you are relying on for this riding?

In BC polling there is likely a bit of a divide between how Vancouver / Vancouver Island poll, and how the interior rural areas poll.  It seems very counterintuitive to me that the Liberals would be the recommended option in that riding, so it's sign to me something might be off in your algorithm.

**Comment by j3camero** [comment]
This seems legit to me, given that Liberal support is way up across BC since the last election.

Looks like there aren't any local riding polls for this riding yet. That means the model is using the latest data available: the 2011 election results. Here's the calculation, roughly.

Liberal support across BC in 2011: 13%
Liberal support in BC from latest regional polls: 30%
Liberal support in Kelowna Lake Country in 2011 (redistributed): 11%

Raw proportional swing projection = 11 \* 30 / 13 = 25

Pretty close to the number displayed on the website currently (28). The reason it doesn't match the website exactly is because the projections for all the parties get normalized so they add up to 1, which jostles them all slightly.

I'll close the issue for now, but that doesn't mean it's closed for discussion.

**Comment by j3camero** [comment]
Not denying that there's an issue here, btw. The limitation of the proportional swing model based purely on 2011 election results is well known. But without recent local riding poll data, it's the best we've got.

**Comment by KelseyDH** [comment]
In light of this news it also doesn't seem as unreasonable since the Green candidate dropped out in that riding:  http://www.huffingtonpost.ca/2015/07/17/gary-adams-green-party-li_n_7819054.html
